language: rust
dist: xenial

cache:
  cargo: true

env:
  global:
    - CARGO_TARGET_DIR=target
    - AUTHORIZED_USERS="luke,leia"

matrix:
  fast_finish: true
  allow_failures:
    - rust: nightly
  include:
    - rust: stable
      before_install:
        - rustup component add rustfmt-preview
        - rustup component add clippy-preview
      script:
        - cargo fmt -- --check
        - cargo test
    - rust: beta
      script:
        - cargo test
    - rust: nightly
      script:
        - cargo test

notifications:
  email:
    on_success: never